# This rule is not used by the project replica-master itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the apps.shieldx.local.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: replica-master
    app.kubernetes.io/managed-by: kustomize
  name: replicamaster-editor-role
rules:
- apiGroups:
  - apps.shieldx.local
  resources:
  - replicamasters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.shieldx.local
  resources:
  - replicamasters/status
  verbs:
  - get
